/**
 * Downloads the three typefaces named in SPEC §2.2 and self-hosts them.
 *
 * §10 requires the faces be self-hosted as woff2 subsets and explicitly forbids
 * loading them from Google's CDN. Fetching them once at build time and
 * committing the result satisfies both: the CDN is used as a source of files,
 * never as a runtime dependency, and a reader's browser talks only to this
 * origin.
 *
 * Run with `npm run build:fonts`. Commit `public/fonts/` and the generated
 * `src/styles/fonts.css`, the same way §3 has the catalog build commit its
 * outputs. There is no need to run this again unless a face changes.
 */
import { writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';

// A browser UA is required: Google serves older formats to anything it does
// not recognise, and we specifically want woff2.
const UA =
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';

/** Only the latin subset is kept — see the note in fonts.css. */
const SUBSET = 'latin';

const FACES = [
  { family: 'Bodoni Moda', css: 'Bodoni+Moda:opsz,wght@6..96,600', weight: 600, style: 'normal', file: 'bodoni-moda-600' },
  { family: 'Source Serif 4', css: 'Source+Serif+4:opsz,wght@8..60,400', weight: 400, style: 'normal', file: 'source-serif-4-400' },
  { family: 'Source Serif 4', css: 'Source+Serif+4:opsz,wght@8..60,600', weight: 600, style: 'normal', file: 'source-serif-4-600' },
  { family: 'Source Serif 4', css: 'Source+Serif+4:ital,opsz,wght@1,8..60,400', weight: 400, style: 'italic', file: 'source-serif-4-400-italic' },
  { family: 'IBM Plex Mono', css: 'IBM+Plex+Mono:wght@400', weight: 400, style: 'normal', file: 'ibm-plex-mono-400' },
  { family: 'IBM Plex Mono', css: 'IBM+Plex+Mono:wght@500', weight: 500, style: 'normal', file: 'ibm-plex-mono-500' },
];

const FONT_DIR = join(process.cwd(), 'public', 'fonts');
const CSS_OUT = join(process.cwd(), 'src', 'styles', 'fonts.css');

async function fetchText(url) {
  const response = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!response.ok) throw new Error(`${response.status} ${response.statusText} for ${url}`);
  return response.text();
}

/** Pull the woff2 URL and unicode-range out of the requested subset's block. */
function extractSubset(css, subset) {
  const blocks = css.split('/*').map((chunk) => `/*${chunk}`);
  for (const block of blocks) {
    if (!block.startsWith(`/* ${subset} */`)) continue;
    const url = block.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1];
    const range = block.match(/unicode-range:\s*([^;]+);/)?.[1]?.trim();
    if (url) return { url, range };
  }
  return null;
}

async function main() {
  await mkdir(FONT_DIR, { recursive: true });
  const rules = [];

  for (const face of FACES) {
    const api = `https://fonts.googleapis.com/css2?family=${face.css}&display=swap`;
    const css = await fetchText(api);
    const found = extractSubset(css, SUBSET);
    if (!found) throw new Error(`No "${SUBSET}" subset found for ${face.family} ${face.weight}`);

    const response = await fetch(found.url, { headers: { 'User-Agent': UA } });
    if (!response.ok) throw new Error(`${response.status} downloading ${found.url}`);
    const bytes = Buffer.from(await response.arrayBuffer());
    await writeFile(join(FONT_DIR, `${face.file}.woff2`), bytes);

    console.log(`  ${face.file}.woff2  ${(bytes.length / 1024).toFixed(1)} kB`);

    rules.push(
      [
        '@font-face {',
        `  font-family: '${face.family}';`,
        `  font-style: ${face.style};`,
        `  font-weight: ${face.weight};`,
        // swap, so prose is readable immediately rather than invisible while a
        // face downloads. The fallback stacks in tokens.css are metric-similar
        // enough that the swap is not violent.
        '  font-display: swap;',
        `  src: url('/fonts/${face.file}.woff2') format('woff2');`,
        found.range ? `  unicode-range: ${found.range};` : null,
        '}',
      ]
        .filter(Boolean)
        .join('\n'),
    );
  }

  const header = [
    '/*',
    ' * GENERATED by scripts/build-fonts.mjs — do not edit by hand.',
    ' *',
    ' * The three faces of SPEC §2.2, self-hosted per §10. Latin subset only:',
    ' * every glyph on this site is Latin text, digits, or a handful of symbols,',
    ' * and shipping Cyrillic and Greek coverage nobody renders would multiply the',
    ' * download for nothing. If a future explorable needs another script, add its',
    ' * subset to SUBSET in the script and re-run it.',
    ' */',
    '',
  ].join('\n');

  await writeFile(CSS_OUT, `${header}${rules.join('\n\n')}\n`);
  console.log(`\nWrote ${CSS_OUT}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
